# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
